---
cluster_name: dcos-vagrant
bootstrap_url: http://192.168.65.50
exhibitor_storage_backend: static
master_discovery: static
master_list:
- 192.168.65.90
resolvers:
- 10.0.2.3
superuser_username: admin
superuser_password_hash: "$6$rounds=656000$123o/Qz.InhbkbsO$kn5IkpWm5CplEorQo7jG/27LkyDgWrml36lLxDtckZkCxu22uihAJ4DOJVVnNbsz/Y5MCK3B1InquE6E7Jmh30"
ssh_port: 22
ssh_user: vagrant
agent_list:
- 192.168.65.111
platform: vagrant-virtualbox
check_time: false
public_agent_list:
- 192.168.65.60
exhibitor_zk_hosts: 192.168.65.50:2181
